export interface IHotVideo {
  thumbnail: string;
  id: string;
  title: string;
  publicAt?: Date;
  days: number;
  likes: number;
  dislikes: number;
  views: number;
  date: string;
  description: string;
  tags: string[];
  commentCount: number;
  gapViews: number;
  gapLikes: number;
  gapDislikes: number;
  gapCommentsCount: number;
  commentCountHistory: string;
  viewsHistory: string;
  likesHistory: string;
  dislikesHistory: string;
  duration: number;
  madeForKids: boolean;
  channelInformation: {
    label?: string;
    urlChannel: string;
    id: string;
    subscribe: string;
    views: string;
    title: string;
    numberVideos: string;
    date: string;
    channelThumbnail: string;
    bannerExternalUrl: string;
    publishedAt?: Date;
    description: string;
    tags: string;
  };
}
